local:
  base_path: "/Users/aditikulkarni/Documents/Masters/AI-Projects/04-ML-Models/ensembles-bagging-boosting/"
  raw_data: "data/raw/"
  processed_data: "data/processed/"
  models: "models/"

aws:
  base_path: ".../04-ML-Models/ensembles-bagging-boosting/"
  raw_data: "s3://ml-data-masters/04-ML-Models/data/raw/"
  processed_data: "s3://ml-data-masters/04-ML-Models/data/processed/"
  models: "s3://ml-data-masters/04-ML-Models/models/"
